// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalAccount.Data;

#nullable disable

namespace PersonalAccount.Data.Migrations
{
    [DbContext(typeof(PersonalAccountContext))]
    [Migration("20260407144953_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalAccount.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Inn")
                        .HasColumnType("text")
                        .HasColumnName("inn");

                    b.Property<string>("LoadOptions")
                        .HasColumnType("jsonb")
                        .HasColumnName("load_options");

                    b.HasKey("Id")
                        .HasName("companies_pkey");

                    b.HasIndex(new[] { "Inn" }, "company_inn_ix")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Emploee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("emploees_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("emploees", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.JournalRow", b =>
                {
                    b.Property<long>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Code"));

                    b.Property<long?>("CategoryCode")
                        .HasColumnType("bigint")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision")
                        .HasColumnName("discount");

                    b.Property<long?>("EmploeeCode")
                        .HasColumnType("bigint")
                        .HasColumnName("emploee_code");

                    b.Property<string>("EmploeeName")
                        .HasColumnType("text")
                        .HasColumnName("emploee_name");

                    b.Property<string>("NomenclatureName")
                        .HasColumnType("text")
                        .HasColumnName("nomenclature_name");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<long?>("ProductCode")
                        .HasColumnType("bigint")
                        .HasColumnName("product_code");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<long>("ReceiptNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_number");

                    b.Property<long>("TypeCode")
                        .HasColumnType("bigint")
                        .HasColumnName("type_code");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Code");

                    b.ToTable("journal_rows");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.LinksUserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("links_user_company_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("links_user_company", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("nomenclatures_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("nomenclatures", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Schemaversion", b =>
                {
                    b.Property<int>("Schemaversionsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("schemaversionsid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Schemaversionsid"));

                    b.Property<DateTime>("Applied")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("applied");

                    b.Property<string>("Scriptname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scriptname");

                    b.HasKey("Schemaversionsid")
                        .HasName("PK_schemaversions_Id");

                    b.ToTable("schemaversions", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ChangePeriod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_period");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("discount");

                    b.Property<Guid?>("EmloeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("emloee_id");

                    b.Property<Guid?>("NomenclatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("quantity");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmloeeId");

                    b.HasIndex("NomenclatureId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Category", b =>
                {
                    b.HasOne("PersonalAccount.Data.Models.Company", "Company")
                        .WithMany("Categories")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("categories_company_id_fk");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Emploee", b =>
                {
                    b.HasOne("PersonalAccount.Data.Models.Company", "Company")
                        .WithMany("Emploees")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("emploees_company_id_fk");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.LinksUserCompany", b =>
                {
                    b.HasOne("PersonalAccount.Data.Models.Company", "Company")
                        .WithMany("LinksUserCompanies")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("links_user_company_company_id_fk");

                    b.HasOne("PersonalAccount.Data.Models.User", "User")
                        .WithMany("LinksUserCompanies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("links_user_company_user_id_fk");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Nomenclature", b =>
                {
                    b.HasOne("PersonalAccount.Data.Models.Category", "Category")
                        .WithMany("Nomenclatures")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("nomenclatures_category_id_fk");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Transaction", b =>
                {
                    b.HasOne("PersonalAccount.Data.Models.Company", "Company")
                        .WithMany("Transactions")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("transactions_company_id_fk");

                    b.HasOne("PersonalAccount.Data.Models.Emploee", "Emloee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmloeeId")
                        .HasConstraintName("transactions_emloee_id_fk");

                    b.HasOne("PersonalAccount.Data.Models.Nomenclature", "Nomenclature")
                        .WithMany("Transactions")
                        .HasForeignKey("NomenclatureId")
                        .HasConstraintName("transactions_nomenclature_id_fk");

                    b.Navigation("Company");

                    b.Navigation("Emloee");

                    b.Navigation("Nomenclature");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Category", b =>
                {
                    b.Navigation("Nomenclatures");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Company", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Emploees");

                    b.Navigation("LinksUserCompanies");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Emploee", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.Nomenclature", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalAccount.Data.Models.User", b =>
                {
                    b.Navigation("LinksUserCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
